# Generated by Django 4.0.1 on 2022-01-24 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id_no', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('branch', models.CharField(max_length=2)),
                ('admission_category', models.CharField(max_length=3)),
                ('cast_category', models.CharField(max_length=5)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('dob', models.DateField()),
                ('email_id', models.CharField(max_length=100)),
                ('contact_no_1', models.CharField(max_length=12)),
                ('contact_no_2', models.CharField(max_length=12)),
                ('ssc_result', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hsc_result', models.DecimalField(decimal_places=2, max_digits=5)),
                ('diploma_result', models.DecimalField(decimal_places=2, max_digits=5)),
                ('spi_sem_1', models.DecimalField(decimal_places=2, max_digits=4)),
                ('spi_sem_2', models.DecimalField(decimal_places=2, max_digits=4)),
                ('spi_sem_3', models.DecimalField(decimal_places=2, max_digits=4)),
                ('spi_sem_4', models.DecimalField(decimal_places=2, max_digits=4)),
                ('spi_sem_5', models.DecimalField(decimal_places=2, max_digits=4)),
                ('spi_sem_6', models.DecimalField(decimal_places=2, max_digits=4)),
                ('spi_sem_7', models.DecimalField(decimal_places=2, max_digits=4)),
                ('spi_sem_8', models.DecimalField(decimal_places=2, max_digits=4)),
                ('cpi', models.DecimalField(decimal_places=2, max_digits=4)),
                ('address_1', models.CharField(max_length=150)),
                ('address_2', models.CharField(max_length=150)),
                ('address_3', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('pin_code', models.CharField(max_length=10)),
                ('career_preference', models.CharField(choices=[('H', 'Higher Studies'), ('J', 'Job')], max_length=1)),
                ('internship', models.CharField(max_length=100)),
                ('placement', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('other_placement_1', models.CharField(max_length=100)),
                ('other_placement_2', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=50)),
                ('stu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_details', models.CharField(max_length=50)),
                ('stu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
