# Generated by Django 4.0.1 on 2022-01-24 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_achievements_id_alter_skill_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievements',
            old_name='id',
            new_name='aid',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='id',
            new_name='sid',
        ),
    ]
