# Generated by Django 4.0.1 on 2022-01-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_rename_id_achievements_aid_rename_id_skill_sid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='aid',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='skill',
            name='sid',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
