# Generated by Django 4.0.1 on 2022-02-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_achievements_aid_alter_skill_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batch_year',
            field=models.IntegerField(default=2018),
            preserve_default=False,
        ),
    ]
